<?php /* $Id: _menu.phtml 1071 2011-01-05 20:54:24Z cepa $ */ ?>
<?php
$menu = array();
$menu[] = array('title' => 'browse_projects', 'url' => $this->url(array(), 'projects'), 'action' => 'index');
if ($this->identity && $this->identity->isAdmin())
    $menu[] = array('title' => 'create_a_new_project', 'url' => $this->url(array(), 'projects/new'), 'action' => 'new');
?>
<?= $this->actionMenu($menu) ?>
