<?php /* $Id: _left.phtml 1071 2011-01-05 20:54:24Z cepa $ */ ?>
    <div class="header-box">
        <h1><?= _T('project') ?> <strong><?= $this->escape($this->project->name) ?></strong></h1>
    </div>
    
    <div class="text-frame"><p><?= $this->superEscape($this->project->description) ?></p></div>
    
    <div class="info-frame">        
        <div class="header"><?= _T('details') ?></div>
        <div class="content-box">
            <div class="property">
                <div class="label"><?= _T('access') ?>:</div>
                <div class="content"><?= $this->boolLabel($this->project->is_private, _T('Private'), _T('Public')) ?></div>
            </div>
            <div class="property">
                <div class="label"><?= _T('created_by') ?>:</div>
                <div class="content"><?= $this->userLink($this->project->author->slug, $this->project->author->name) ?></div>
            </div>
            <div class="property">
                <div class="label"><?= _T('updated_by') ?>:</div>
                <div class="content"><?= $this->userLink($this->project->changer->slug, $this->project->changer->name) ?></div>
            </div>
            <div class="property">
                <div class="label"><?= _T('created_at') ?>:</div>
                <div class="content"><?= $this->date($this->project->create_time) ?></div>
            </div>
            <div class="property">
                <div class="label"><?= _T('updated_at') ?>:</div>
                <div class="content"><?= $this->date($this->project->update_time) ?></div>
            </div>
        </div>
    </div>
    
    <?php if (count($this->milestones) > 0): ?>
        <div class="info-frame">        
            <div class="header"><?= _T('milestones') ?></div>
            <div class="content-box">
                <ul class="list">
                    <?php foreach ($this->milestones as $milestone): ?>
                        <li><?= $this->milestoneLink($this->project['slug'], $milestone['slug'], $milestone['name']) ?></li>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
    <?php endif ?>
    
    <?php if (count($this->components) > 0): ?>
        <div class="info-frame">        
            <div class="header"><?= _T('components') ?></div>
            <div class="content-box">
                <ul class="list">
                    <?php foreach ($this->components as $component): ?>
                        <li><?= $this->componentLink($this->project['slug'], $component['slug'], $component['name']) ?></li>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
    <?php endif ?>
    
    <?php if (count($this->leaders) > 0): ?>
        <div class="info-frame">        
            <div class="header"><?= _T('leaders') ?></div>
            <div class="content-box">
                <?= $this->partial('index/_members.phtml', array('members' => $this->leaders))?>
            </div>
        </div>
    <?php endif ?>
    
    <?php if (count($this->developers) > 0): ?>
        <div class="info-frame">        
            <div class="header"><?= _T('developers') ?></div>
            <div class="content-box">
                <?= $this->partial('index/_members.phtml', array('members' => $this->developers))?>
            </div>
        </div>
    <?php endif ?>
    
    <?php if (count($this->observers) > 0): ?>
        <div class="info-frame">        
            <div class="header"><?= _T('observers') ?></div>
            <div class="content-box">
                <?= $this->partial('index/_members.phtml', array('members' => $this->observers))?>
            </div>
        </div>
    <?php endif ?>
