<?php /* $Id: history.phtml 1071 2011-01-05 20:54:24Z cepa $ */ ?>
<?= $this->render('index/_menu.phtml') ?>

<div class="index-left-box">
    <?= $this->render('index/_left.phtml') ?>
</div>

<div class="index-main-box">
    <div class="header-box">
        <h1><?= _T('history_of_changes') ?></h1>
    </div>
    <?= $this->partial('_changes.phtml', array(
        'changes' => $this->changes,
        'fields' => ChangeProcessor::$projectFields
    )) ?>
</div>

