<?php /* $Id: show.phtml 1071 2011-01-05 20:54:24Z cepa $ */ ?>
<div class="action-menu">
    <?= $this->render('notes/_menu.phtml') ?>
    <?= $this->render('notes/_record_menu.phtml') ?>
</div>

<div class="index-left-box">
    <?= $this->render('notes/_left.phtml') ?>
</div>

<div class="index-main-box">
    <div class="header-box">
        <a class="issue-header" href="<?= $this->url(array('project_slug' => $this->project->slug, 'note_slug' => $this->note->slug), 'project/notes/show') ?>"><?= $this->escape($this->note->title) ?></a>
    </div>
    <div class="text-frame">
        <p><?= $this->superEscape($this->note->content) ?></p>
    </div>
</div>
