<?php /* $Id: index.phtml 1071 2011-01-05 20:54:24Z cepa $ */ ?>
<div class="index-left-box">

    <?= $this->render('_welcome.phtml') ?>

    <div class="header-box">
        <?php if ($this->identity): ?>
            <h1><?= _T('my_projects') ?></h1>
        <?php else: ?>
            <h1><?= _T('public_projects') ?></h1>
        <?php endif ?>
    </div>
    <?= $this->partial('_projects_list.phtml', array('projects' => $this->identityProjects)) ?>
    
</div>

<div class="index-main-box">
    
    <?php if ($this->identity): ?>
        <?= $this->myGrid ?>
        <div style="height:20px;"></div>
    <?php endif ?>
    
    <?= $this->latestGrid ?>
    <div style="height:20px;"></div>

    <div class="header-box">
        <h1><?= _T('latest_activity') ?></h1>
    </div>
    <?= $this->partial('_log.phtml', array('log' => $this->activity)) ?>
    
</div>

