<?php /* $Id: edit.phtml 87 2011-01-05 20:54:24Z cepa $ */ ?>
<div class="action-menu">
    <?= $this->render('users/_menu.phtml') ?>
    <?= $this->render('users/_record_menu.phtml') ?>
</div>

<div class="index-left-box">
    <?= $this->render('users/_left.phtml') ?>
</div>

<div class="index-main-box">
    <div class="header-box">
        <h1><?= _T('edit') ?></h1>
    </div>
    <?= $this->form ?>
</div>

