<?php /* $Id: register.phtml 1071 2011-01-05 20:54:24Z cepa $ */ ?>
<div class="action-menu">
    <?= $this->render('auth/_menu.phtml') ?>
</div>

<div class="header-box">
    <h1><?= _T('signup_for_a_new_account') ?></h1>
</div>

<?= $this->form ?>

<div id="dialog" title="Accept Licence">
    <p>This is a licence</p>
    <p>Are you sure do you accept?</p>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $("#dialog").dialog({
            autoOpen: false,
            modal: true,
            buttons : {
                        "Confirm" : function() {
                            $(this).dialog("close");
                        },
                        "Cancel" : function() {
                            $("#accept_licence").removeAttr('checked');
                            $(this).dialog("close");
                        }
                    }
        });
        $("#accept_licence").click(function() {
            var checked = $(this).is(':checked');
            if (checked) {
                $("#dialog").dialog("open");
            }
        });
    });
</script>