<?php /* $Id: _left.phtml 1071 2011-01-05 20:54:24Z cepa $ */ ?>
    <div class="header-box">
        <h1><?= _T('milestone') ?> <strong><?= $this->escape($this->project->name) ?>-<?= $this->escape($this->milestone->name) ?></strong></h1>
    </div>
    
    <div class="text-frame"><p><?= $this->superEscape($this->milestone->description) ?></p></div>
    
    <div class="info-frame">        
        <div class="header"><?= _T('details') ?></div>
        <div class="content-box">
            <div class="property">
                <div class="label"><?= _T('project') ?>:</div>
                <div class="value"><?= $this->projectLink($this->project->slug, $this->project->name) ?>&nbsp;</div>
            </div>
            <div class="property">
                <div class="label"><?= _T('created_by') ?>:</div>
                <div class="value"><?= $this->userLink($this->milestone->author->slug, $this->milestone->author->name) ?>&nbsp;</div>
            </div>
            <div class="property">
                <div class="label"><?= _T('updated_by') ?>:</div>
                <div class="value"><?= $this->userLink($this->milestone->changer->slug, $this->milestone->changer->name) ?>&nbsp;</div>
            </div>
            <div class="property">
                <div class="label"><?= _T('created_at') ?>:</div>
                <div class="content"><?= $this->date($this->milestone->create_time) ?></div>
            </div>
            <div class="property">
                <div class="label"><?= _T('updated_at') ?>:</div>
                <div class="content"><?= $this->date($this->milestone->update_time) ?></div>
            </div>
        </div>
    </div>
