<?php /* $Id: _footer.phtml 1353 2012-12-26 20:46:41Z cepa $ */ ?>
<div id="footer-box" style="padding-top:10px; margin-top:10px; border-top:1px dotted #888888">
<span style="float:left">Powered by <a href="http://https://github.com/koweb/Vermis">Vermis</a></span>
<span style="float:right">&copy; <?= date('Y') ?> <a href="http://https://github.com/koweb/Vermis">Cask Code, KOWeb</a></span>
</div>

</body>
</html>
