<?php /* $Id: _header.phtml 1071 2011-01-05 20:54:24Z cepa $ */ ?>
<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
<head>

    <base href="<?= $this->config->baseHost.$this->config->baseUri ?>" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="Author" content="cepa" />

    <title>Vermis</title>
    
    <link rel="stylesheet" type="text/css" href="css/style.css"/>
    <link rel="icon" type="image/png" href="gfx/favicon.png">

</head>
<body>
