<?php /* $Id: activity.phtml 1071 2011-01-05 20:54:24Z cepa $ */ ?>
<?= $this->render('_header.phtml') ?>
<?php $hasComment = (isset($this->misc) && isset($this->misc['comment'])) ?>

<a href="<?= $this->config->baseHost ?><?= $this->url(array('user_slug' => $this->user->slug), 'users/show') ?>"><?= $this->user->name ?></a>
<?= _T($this->resourceType.' '.$this->action) ?>: 
<a href="<?= $this->config->baseHost ?><?= $this->logUrl($this->resourceType, $this->params) ?>"><?= $this->message ?></a>

<br />

<?php if ($hasComment): ?>
    <div style="padding:20px;"><q><?= $this->superEscape($this->misc['comment']) ?></q></div>
<?php endif ?>

<?php
switch ($this->resourceType) {
    case Log::TYPE_PROJECT: $fields = ChangeProcessor::$projectFields; break;
    case Log::TYPE_COMPONENT: $fields = ChangeProcessor::$componentFields; break;
    case Log::TYPE_ISSUE: $fields = ChangeProcessor::$issueFields; break;
    case Log::TYPE_MILESTONE: $fields = ChangeProcessor::$milestoneFields; break;
    case Log::TYPE_NOTE: $fields = ChangeProcessor::$noteFields; break;
    default: $fields = array();
}
?>

<?php if (!empty($this->changes) && !$hasComment): ?>
    <?= $this->partial('_changes.phtml', array(
        'changes' => $this->changes,
        'fields' => $fields
    )) ?>
<?php endif ?>

<?= $this->render('_footer.phtml') ?>
