<?php /* $Id: remind-password.phtml 1071 2011-01-05 20:54:24Z cepa $ */ ?>
<?= $this->render('_header.phtml') ?>

<?= _T('dont_remember_your_password')?><br />
<?= _T('just_click')?> <a href="<?= $this->config->baseHost ?><?= $this->url(array('user_slug' => $this->user->slug, 'hash' => $this->user->confirm_hash), 'users/generate-password') ?>"><?= _T('here')?></a>
<?= _T('to_generate_a_new_password')?>.

<?= $this->render('_footer.phtml') ?>
