<?php /* $Id: _record_menu.phtml 87 2011-01-05 20:54:24Z cepa $ */ ?>
<?
$menu = array();
if ($this->identity) {
    if ($this->identity->isAdmin()) 
        $menu[] = array('title' => 'delete', 'url' => $this->url(array('project_slug' => $this->project->slug, 'component_slug' => $this->component->slug), 'project/components/delete'), 'action' => 'delete', 'confirm' => true, 'float' => 'right'); 
    if ($this->identity->isAdmin() || $this->projectRole != Project_Member::ROLE_OBSERVER)
        $menu[] = array('title' => 'edit', 'url' => $this->url(array('project_slug' => $this->project->slug, 'component_slug' => $this->component->slug), 'project/components/edit'), 'action' => 'edit', 'float' => 'right');
}
$menu[] = array('title' => 'history', 'url' => $this->url(array('project_slug' => $this->project->slug, 'component_slug' => $this->component->slug), 'project/components/history'), 'action' => 'history', 'float' => 'right');
$menu[] = array('title' => 'show', 'url' => $this->url(array('project_slug' => $this->project->slug, 'component_slug' => $this->component->slug), 'project/components/show'), 'action' => 'show', 'float' => 'right');
?>
<?= $this->actionMenu($menu) ?>
