<?php /* $Id: _menu.phtml 1071 2011-01-05 20:54:24Z cepa $ */ ?>
<?
$menu = array();  
$menu[] = array('title' => 'log_in', 'url' => $this->url(array(), 'auth/login'), 'action' => 'login');
$menu[] = array('title' => "dont_remember_your_password", 'url' => $this->url(array(), 'users/remind-password'), 'action' => 'remind-password');
$menu[] = array('title' => "signup_for_a_new_account", 'url' => $this->url(array(), 'users/register'), 'action' => 'register');
?>
<?= $this->actionMenu($menu) ?>
