<?php /* $Id: login.phtml 87 2011-01-05 20:54:24Z cepa $ */ ?>
<div class="action-menu">
    <?= $this->render('auth/_menu.phtml') ?>
</div>

<div id="login-box">
    <div class="header-box"><h1>Vermis</h1></div>
    <?= $this->form ?>
    <? if (Application::getInstance()->isDemo()): ?>
        <p style="text-align:center"><?= _T('demo_message')?></p>
    <? endif ?>
    <p style="text-align:center">
        <a href="<?= $this->url(array(), 'users/register') ?>"><?= _T('signup_for_a_new_account') ?></a> |
        <a href="<?= $this->url(array(), 'users/remind-password') ?>"><?= _T('dont_remember_your_password') ?></a> 
    </p>
</div>