<?php /* $Id: _changes.phtml 1071 2011-01-05 20:54:24Z cepa $ */ ?>
<?php foreach ($this->changes as $change): ?>
    <div class="changes">
        <div>
            <?php if (isset($change['changer_slug']) && isset($change['changer_name']) && isset($change['update_time'])): ?>
                <?= $this->userLink($change['changer_slug'], $change['changer_name']) ?>
                <?= _T('made_changes') ?> - 
                <?= $this->date($change['update_time']) ?> 
            <?php endif ?>
        </div>
        <table>
        <?php foreach ($this->fields as $key => $options): ?>
            <?php if (array_key_exists($key, $change)): $value = $change[$key]; ?>
                <tr>
                    <td><?= _T($options['title']) ?></td>
                    <td>=&gt;</td>
                    <td>
                        <?php 
                        if (isset($options['decorator'])) {
                            $args = array();
                            $params = $options['params'];
                            foreach ($params as $param) {
                                if (array_key_exists($param, $change))
                                    $param = $change[$param];
                                $args[] = $param;
                            }
                            echo call_user_func_array(array($this, $options['decorator']), $args);
                            
                        } else if (is_string($value)) echo $this->superEscape($value);
                        else if (is_bool($value)) echo ($value ? _T('true') : _T('false'));
                        else echo $this->superEscape((string) $value);
                        ?>
                    </td>
                </tr>
            <?php endif ?>
        <?php endforeach ?>
        </table>
    </div>
<?php endforeach ?>
