<?php /* $Id: _flash_messages.phtml 1071 2011-01-05 20:54:24Z cepa $ */ ?>
<?php $messages = FreeCode_FlashMessages::getInstance()->getMessagesAndClear() ?>

<?php if (count($messages) > 0): ?>
    <div id="flash-messages-box" class="popup">
        <div class="shadow">
            <div class="content">
                <?php foreach ($messages as $message => $flag): ?>
                    <div><?= $this->escape(_T($message)) ?></div>
                <?php endforeach ?>
            </div>
        </div>
    </div>
    
    <script type="text/javascript">
    $('document').ready(function(){
        $('#flash-messages-box').fadeTo(2000, 1, function(){
        	$('#flash-messages-box').fadeOut(1000);
        });
        $('#flash-messages-box').click(function(){
            $('#flash-messages-box').hide();
        });
    });
    </script>
<?php endif ?>
