<?php /* $Id: _footer.phtml 1353 2012-12-26 20:46:41Z cepa $ */ ?>
<div id="footer-box">
	<span style="float:left">
    <?
    $version = VERMIS_VERSION;
    $svnRev = VERMIS_SVN_REVISION;
    ?>
    Powered by <a href="http://vermis.hellworx.com">Vermis-<?= $version ?>-<?= $svnRev ?></a>
	</span>
	<span style="float:right">&copy; <?= date('Y') ?> <a href="http://www.hellworx.com">HellWorx Software</a></span>
</div>

</body>
</html>
