<?php /* $Id: _footer.phtml 126 2011-01-29 23:37:39Z cepa $ */ ?>
<div id="footer-box">
	<span style="float:left">
    <?
    $version = VERMIS_VERSION;
    $svnRev = VERMIS_SVN_REVISION;
    ?>
    Powered by <a href="http://vermis.ognisco.com">Vermis-<?= $version ?>-<?= $svnRev ?></a>
	</span>
	<span style="float:right">&copy; <?= date('Y') ?> <a href="http://www.ognisco.com">Ognisco</a></span>
</div>

</body>
</html>
