<?php /* $Id: _identity.phtml 87 2011-01-05 20:54:24Z cepa $ */ ?>
        <div id="identity-box">
            <?= _T('logged_as') ?> <a class="strong" href="<?= $this->url(array('user_slug' => $this->identity->slug), 'users/show') ?>"><?= $this->escape($this->identity->name) ?></a> |
            <? if ($this->activeModule != 'default'): ?>
                <a href="<?= $this->url(array(), 'index') ?>"><?= $this->identity ? _T('dashboard') : _T('home') ?></a> |
            <? endif ?>
            <a href="<?= $this->url(array(), 'auth/logout') ?>"><?= _T('log_out') ?></a>
        </div>
