<?php /* $Id: history.phtml 87 2011-01-05 20:54:24Z cepa $ */ ?>
<div class="action-menu">
    <?= $this->render('issues/_menu.phtml') ?>
    <?= $this->render('issues/_record_menu.phtml') ?>
</div>

<div class="index-left-box">
    <?= $this->render('issues/_left.phtml') ?>
</div>

<div class="index-main-box">
    <div class="header-box">
        <h1><?= _T('history_of_changes') ?></h1>
    </div>
    <?= $this->partial('_changes.phtml', array(
        'changes' => $this->changes,
        'fields' => ChangeProcessor::$issueFields
    )) ?>
</div>

