<?php /* $Id: new.phtml 1071 2011-01-05 20:54:24Z cepa $ */ ?>
<div class="action-menu">
    <?= $this->render('issues/_menu.phtml') ?>
</div>

<div class="header-box">
    <h1><?= _T('create_a_new_issue') ?></h1>
</div>

<?= $this->form ?>

<script type="text/javascript">
    function updateComponents() {
        $.ajax({
            url: "issues/components/?project_id=" + $('#project_id').val(),
             dataType: 'application/json; charset=utf-8',
            cache: false,
            complete:function (response) {
                    $('#component_id').text('');
                    var result = JSON.parse(response.responseText);
                    $.each(result, function(_, value) {
                        $('#component_id').append($("<option />").val(value.id).text(value.name));
                    });
                }
        });
    }
    
    function updateMilestones() {
        $.ajax({
            url: "issues/milestones/?project_id=" + $('#project_id').val(),
             dataType: 'application/json; charset=utf-8',
            cache: false,
            complete:function (response) {
                    $('#milestone_id').text('');
                    var result = JSON.parse(response.responseText);
                    $.each(result, function(_, value) {
                        $('#milestone_id').append($("<option />").val(value.id).text(value.name));
                    });
                }
        });
    }
    
    $(document).ready(updateComponents);
    $(document).ready(updateMilestones);
    
    $('#project_id').change(updateComponents);
    $('#project_id').change(updateMilestones);
</script>